DROP TABLE STUDENTS;
DROP SEQUENCE SEC1;
DROP SEQUENCE SEC2;
 
CREATE TABLE STUDENTS (
    ID VARCHAR2(20) PRIMARY KEY,
    DOA DATE,
    DEPARTMENT VARCHAR2(20),
    PROGRAM VARCHAR2(20),
    SEC VARCHAR2(20)
);
 
CREATE SEQUENCE SEC1 START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEC2 START WITH 1 INCREMENT BY 1;
 
 
CREATE OR REPLACE TRIGGER INSERT_STUDENT_ID
BEFORE INSERT
ON STUDENTS
FOR EACH ROW
DECLARE
    pragma autonomous_transaction;
    LAST_TWO_DIGITS VARCHAR2(20);
    IDNEW VARCHAR2(20);
    TEMP VARCHAR2(20);
BEGIN
 
IF :NEW.SEC = '1' THEN
SELECT SEC1.NEXTVAL INTO TEMP FROM DUAL;
ELSE
SELECT SEC2.NEXTVAL INTO TEMP FROM DUAL;
END IF;
 
SELECT TO_CHAR(:NEW.DOA, 'YY') INTO LAST_TWO_DIGITS FROM DUAL;
 
IDNEW := LAST_TWO_DIGITS || '00' || :NEW.DEPARTMENT || :NEW.PROGRAM || :NEW.SEC ||  '0' || TEMP;
 
:NEW.ID := IDNEW;
 
commit;
END;
/
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','1');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','2');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','2');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','1');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','1');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','2');
INSERT INTO STUDENTS VALUES ('0',TO_DATE('2019-11-04', 'yyyy-mm-dd'),'4','1','1');
SELECT * FROM STUDENTS;